# Generated by Django 5.1.7 on 2025-03-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numControl', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('primerAp', models.CharField(max_length=100)),
                ('segundoAp', models.CharField(max_length=100)),
                ('fechaNac', models.DateField()),
                ('semestre', models.IntegerField()),
                ('carrera', models.IntegerField()),
            ],
            options={
                'db_table': 'alumnos',
            },
        ),
    ]
